---
output: github_document
editor_options:
  markdown:
    wrap:      80
    canonical: false
---

```{r config}
#| echo: false
GITHUB_USERNAME <- "wldkPHD"
AUTHOR_NAME     <- "William L. D. Krenzer, Ph.D"
CREATION_YEAR   <- 2025L

# Objects created automatically (no need to edit)

## Repository configuration objects
profile_url     <- paste0("https://github.com/", GITHUB_USERNAME)
https_clone_url <- git2r::remote_url()
repo_url        <- https_clone_url |> tools::file_path_sans_ext()
repo_name       <- basename(repo_url)

## Software version objects
r_version     <- paste(version$major, version$minor, sep = '.')
rs_version    <- rstudioapi::versionInfo()$long_version
rs_version_dl <- rs_version |> stringr::str_replace('\\+', '-')
q_version     <- quarto::quarto_version()
git_version   <- gitr::git_version()
```

# Repository ``r repo_name``

This GitHub repository is made for storing the code and associated documents for processing the National Institute of Health proposals that are submitted at Duke University on a quarterly basis (e.g., Jan - Mar, Apr - Jun, Jul - Sep, Oct - Dec). This code is made specifically for processing the raw .csv files from the various internal websites at Duke (e..g,  SPS, RCR Tracker, LDap, etc.) and preparing the an import file for the REDCap _Proposal Award Tracker_.

For those not affiliated with Duke University, this repository as a whole will not be useful. However, the code may be helpful, and we welcome and commits if errors found or ways for making the processing more symplistic.

# License

<!-- TODO: Choose a license and update this section, if necessary -->

[Repository `r repo_name`](`r repo_url`) © `r CREATION_YEAR` by
[`r AUTHOR_NAME`](`r profile_url`) is licensed under [CC BY-NC 4.0][license].
Please see the [license file][licfile].

[license]: https://creativecommons.org/licenses/by-nc/4.0

[licfile]: LICENSE.md

## Attributions

### Rstudio project template

This project makes use of the [rproj-template][selflink] Github template
created by [Daniel Morillo][profile] and licensed under the 
[Creative Commons Attribution 4.0 International license][repo_lic].

[selflink]: https://github.com/DaniMori/rproj-template

[profile]: https://github.com/DaniMori

[repo_lic]: https://creativecommons.org/licenses/by/4.0

<!-- TODO: Add attributions to other software components, if necessary -->

### <Software component>

# Project installation

## Software components

Start by installing the following software components:

- [R version `r r_version`][R]:
  In Windows, using the [binary installer][inst] is recommended.

[R]: https://cran.rstudio.com/bin/windows/base/old/`r r_version`/
[inst]: https://cran.rstudio.com/bin/windows/base/old/`r r_version`/R-`r r_version`-win.exe

- [Rstudio Desktop][RS]: Although not strictly necessary, it is recommended
  to install the Rstudio IDE; for strict reproducibility, use build
  [`r rs_version` for Windows 10/11][RSv].

[RS]: https://posit.co/download/rstudio-desktop/

[RSv]: https://download1.rstudio.org/electron/windows/RStudio-`r rs_version_dl`.exe

- [Quarto publishing system][Q]: An additional component used by Rstudio to
generate and publish literate computing outputs. For strict reproducibility
please use build `r q_version`; On Windows, use [the 64-bit installer][QW].

[Q]: https://quarto.org/

[QW]: https://github.com/quarto-dev/quarto-cli/releases/download/v`r q_version`/quarto-`r q_version`-win.msi

- [Git client][G]: Install the Git client in order to be able to clone locally
  the project repository.
  On Windows, use [the 64-bit Windows installer][GW].

[G]: https://git-scm.com/download

[GW]: https://github.com/git-for-windows/git/releases/download/v`r git_version`.windows.1/Git-`r git_version`-64-bit.exe

# Repository structure

Below is a work in progress and has not yet been updated.

The file structure of this repository is as follows:

```
`r repo_name`
|
|--- apps         (To store apps, e.g. in Shiny)
|
|--- dat          (To store input datasets; must NEVER be checked-in to Github)
|
|--- doc          (To store important documentation of the project)
|    |
|    |--- minutes (To store meeting minutes)
|
|--- notebooks    (Notebooks to explore data and test processes live here)
|
|--- output       (Processing outputs; files must be individually "checked-in"
|                 when necessary)
|
|--- R            (R functions created for this project live here)
|
|--- renv         (System library necesssary for `renv` to work. DON'T TOUCH)
|
|--- src          (Source scripts that implement the main processes)
|
|--- www          (Project assets, e.g., images, bibliography files, etc.)
```

Use the folders as indicated to store the different files and generate the
outputs of the processes.
